loja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedido/urls.py
from django.urls import path
from . import views

app_name = 'pedido'

urlpatterns = [
    path('pagar/<int:pk>', views.Pagar.as_view(), name='pagar'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),
    path('lista/', views.Lista.as_view(), name='lista'),
    path('detalhe/<int:pk>', views.Detalhe.as_view(), name='detalhe'),
]

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.Criar.as_view(), name='criar'),
    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

pedido/models.py
from django.db import models
from django.contrib.auth.models import User


class Pedido(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.FloatField()
    qtd_total = models.PositiveIntegerField()
    status = models.CharField(
        default="C",
        max_length=1,
        choices=(
            ('A', 'Aprovado'),
            ('C', 'Criado'),
            ('R', 'Reprovado'),
            ('P', 'Pendente'),
            ('E', 'Enviado'),
            ('F', 'Finalizado'),
        )
    )

    def __str__(self):
        return f'Pedido N. {self.pk}'


class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    produto = models.CharField(max_length=255)
    produto_id = models.PositiveIntegerField()
    variacao = models.CharField(max_length=255)
    variacao_id = models.PositiveIntegerField()
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    quantidade = models.PositiveIntegerField()
    imagem = models.CharField(max_length=2000)

    def __str__(self):
        return f'Item do {self.pedido}'

    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens do pedido'

perfil/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models


class PerfilForm(forms.ModelForm):
    class Meta:
        model = models.Perfil
        fields = '__all__'
        exclude = ('usuario',)


class UserForm(forms.ModelForm):
    password = forms.CharField(
        required=False,
        widget=forms.PasswordInput(),
        label='Senha',
    )

    password2 = forms.CharField(
        required=False,
        widget=forms.PasswordInput(),
        label='Confirmação senha'
    )

    def __init__(self, usuario=None, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.usuario = usuario

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password',
                  'password2', 'email')

    def clean(self, *args, **kwargs):
        data = self.data
        cleaned = self.cleaned_data
        validation_error_msgs = {}

        usuario_data = cleaned.get('username')
        email_data = cleaned.get('email')
        password_data = cleaned.get('password')
        password2_data = cleaned.get('password2')

        usuario_db = User.objects.filter(username=usuario_data).first()
        email_db = User.objects.filter(email=email_data).first()

        error_msg_user_exists = 'Usuário já existe'
        error_msg_email_exists = 'E-mail já existe'
        error_msg_password_match = 'As duas senhas não conferem'
        error_msg_password_short = 'Sua senha precisa de pelo menos 6 caracteres'
        error_msg_required_field = 'Este campo é obrigatório.'

        # Usuários logados: atualização
        if self.usuario:
            if usuario_db:
                if usuario_data != usuario_db.username:
                    validation_error_msgs['username'] = error_msg_user_exists

            if email_db:
                if email_data != email_db.email:
                    validation_error_msgs['email'] = error_msg_email_exists

            if password_data:
                if password_data != password2_data:
                    validation_error_msgs['password'] = error_msg_password_match
                    validation_error_msgs['password2'] = error_msg_password_match

                if len(password_data) < 6:
                    validation_error_msgs['password'] = error_msg_password_short

        # Usuários não logados: cadastro
        else:
            if usuario_db:
                validation_error_msgs['username'] = error_msg_user_exists

            if email_db:
                validation_error_msgs['email'] = error_msg_email_exists

            if not password_data:
                validation_error_msgs['password'] = error_msg_required_field

            if not password2_data:
                validation_error_msgs['password2'] = error_msg_required_field

            if password_data != password2_data:
                validation_error_msgs['password'] = error_msg_password_match
                validation_error_msgs['password2'] = error_msg_password_match

            if len(password_data) < 6:
                validation_error_msgs['password'] = error_msg_password_short

        if validation_error_msgs:
            raise(forms.ValidationError(validation_error_msgs))

pedido/views.py
from django.shortcuts import redirect, reverse
from django.views.generic import ListView, DetailView
from django.views import View
# from django.http import HttpResponse
from django.contrib import messages

from produto.models import Variacao
from .models import Pedido, ItemPedido

from utils import utils


class DispatchLoginRequiredMixin(View):
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('perfil:criar')

        return super().dispatch(*args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(usuario=self.request.user)
        return qs


class Pagar(DispatchLoginRequiredMixin, DetailView):
    template_name = 'pedido/pagar.html'
    model = Pedido
    pk_url_kwarg = 'pk'
    context_object_name = 'pedido'


class SalvarPedido(View):
    template_name = 'pedido/pagar.html'

    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(
                self.request,
                'Você precisa fazer login.'
            )
            return redirect('perfil:criar')

        if not self.request.session.get('carrinho'):
            messages.error(
                self.request,
                'Seu carrinho está vazio.'
            )
            return redirect('produto:lista')

        carrinho = self.request.session.get('carrinho')
        carrinho_variacao_ids = [v for v in carrinho]
        bd_variacoes = list(
            Variacao.objects.select_related('produto')
            .filter(id__in=carrinho_variacao_ids)
        )

        for variacao in bd_variacoes:
            vid = str(variacao.id)

            estoque = variacao.estoque
            qtd_carrinho = carrinho[vid]['quantidade']
            preco_unt = carrinho[vid]['preco_unitario']
            preco_unt_promo = carrinho[vid]['preco_unitario_promocional']

            error_msg_estoque = ''

            if estoque < qtd_carrinho:
                carrinho[vid]['quantidade'] = estoque
                carrinho[vid]['preco_quantitativo'] = estoque * preco_unt
                carrinho[vid]['preco_quantitativo_promocional'] = estoque * \
                    preco_unt_promo

                error_msg_estoque = 'Estoque insuficiente para alguns '\
                    'produtos do seu carrinho. '\
                    'Reduzimos a quantidade desses produtos. Por favor, '\
                    'verifique quais produtos foram afetados a seguir.'

            if error_msg_estoque:
                messages.error(
                    self.request,
                    error_msg_estoque
                )

                self.request.session.save()
                return redirect('produto:carrinho')

        qtd_total_carrinho = utils.cart_total_qtd(carrinho)
        valor_total_carrinho = utils.cart_totals(carrinho)

        pedido = Pedido(
            usuario=self.request.user,
            total=valor_total_carrinho,
            qtd_total=qtd_total_carrinho,
            status='C',
        )

        pedido.save()

        ItemPedido.objects.bulk_create(
            [
                ItemPedido(
                    pedido=pedido,
                    produto=v['produto_nome'],
                    produto_id=v['produto_id'],
                    variacao=v['variacao_nome'],
                    variacao_id=v['variacao_id'],
                    preco=v['preco_quantitativo'],
                    preco_promocional=v['preco_quantitativo_promocional'],
                    quantidade=v['quantidade'],
                    imagem=v['imagem'],
                ) for v in carrinho.values()
            ]
        )

        del self.request.session['carrinho']

        return redirect(
            reverse(
                'pedido:pagar',
                kwargs={
                    'pk': pedido.pk
                }
            )
        )


class Detalhe(DispatchLoginRequiredMixin, DetailView):
    model = Pedido
    context_object_name = 'pedido'
    template_name = 'pedido/detalhe.html'
    pk_url_kwarg = 'pk'


class Lista(DispatchLoginRequiredMixin, ListView):
    model = Pedido
    context_object_name = 'pedidos'
    template_name = 'pedido/lista.html'
    paginate_by = 10
    ordering = ['-id']

perfil/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from django.views import View
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
import copy

from . import models
from . import forms


class BasePerfil(View):
    template_name = 'perfil/criar.html'

    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)

        self.carrinho = copy.deepcopy(self.request.session.get('carrinho', {}))

        self.perfil = None

        if self.request.user.is_authenticated:
            self.perfil = models.Perfil.objects.filter(
                usuario=self.request.user
            ).first()

            self.contexto = {
                'userform': forms.UserForm(
                    data=self.request.POST or None,
                    usuario=self.request.user,
                    instance=self.request.user,
                ),
                'perfilform': forms.PerfilForm(
                    data=self.request.POST or None,
                    instance=self.perfil
                )
            }
        else:
            self.contexto = {
                'userform': forms.UserForm(
                    data=self.request.POST or None
                ),
                'perfilform': forms.PerfilForm(
                    data=self.request.POST or None
                )
            }

        self.userform = self.contexto['userform']
        self.perfilform = self.contexto['perfilform']

        if self.request.user.is_authenticated:
            self.template_name = 'perfil/atualizar.html'

        self.renderizar = render(
            self.request, self.template_name, self.contexto)

    def get(self, *args, **kwargs):
        return self.renderizar


class Criar(BasePerfil):
    def post(self, *args, **kwargs):
        if not self.userform.is_valid() or not self.perfilform.is_valid():
            messages.error(
                self.request,
                'Existem erros no formulário de cadastro. Verifique se todos '
                'os campos foram preenchidos corretamente.'
            )

            return self.renderizar

        username = self.userform.cleaned_data.get('username')
        password = self.userform.cleaned_data.get('password')
        email = self.userform.cleaned_data.get('email')
        first_name = self.userform.cleaned_data.get('first_name')
        last_name = self.userform.cleaned_data.get('last_name')

        # Usuário logado
        if self.request.user.is_authenticated:
            usuario = get_object_or_404(
                User, username=self.request.user.username)

            usuario.username = username

            if password:
                usuario.set_password(password)

            usuario.email = email
            usuario.first_name = first_name
            usuario.last_name = last_name
            usuario.save()

            if not self.perfil:
                self.perfilform.cleaned_data['usuario'] = usuario
                print(self.perfilform.cleaned_data)
                perfil = models.Perfil(**self.perfilform.cleaned_data)
                perfil.save()
            else:
                perfil = self.perfilform.save(commit=False)
                perfil.usuario = usuario
                perfil.save()

        # Usário não logado (novo)
        else:
            usuario = self.userform.save(commit=False)
            usuario.set_password(password)
            usuario.save()

            perfil = self.perfilform.save(commit=False)
            perfil.usuario = usuario
            perfil.save()

        if password:
            autentica = authenticate(
                self.request,
                username=usuario,
                password=password
            )

            if autentica:
                login(self.request, user=usuario)

        self.request.session['carrinho'] = self.carrinho
        self.request.session.save()

        messages.success(
            self.request,
            'Seu cadastro foi criado ou atualizado com sucesso.'
        )

        messages.success(
            self.request,
            'Você fez login e pode concluir sua compra.'
        )

        return redirect('produto:carrinho')
        return self.renderizar


class Atualizar(View):
    def get(self, *args, **kwargs):
        return HttpResponse('Atualizar')


class Login(View):
    def post(self, *args, **kwargs):
        username = self.request.POST.get('username')
        password = self.request.POST.get('password')

        if not username or not password:
            messages.error(
                self.request,
                'Usuário ou senha inválidos.'
            )
            return redirect('perfil:criar')

        usuario = authenticate(
            self.request, username=username, password=password)

        if not usuario:
            messages.error(
                self.request,
                'Usuário ou senha inválidos.'
            )
            return redirect('perfil:criar')

        login(self.request, user=usuario)

        messages.success(
            self.request,
            'Você fez login no sistema e pode concluir sua compra.'
        )
        return redirect('produto:carrinho')


class Logout(View):
    def get(self, *args, **kwargs):
        carrinho = copy.deepcopy(self.request.session.get('carrinho'))

        logout(self.request)

        self.request.session['carrinho'] = carrinho
        self.request.session.save()

        return redirect('produto:lista')

perfil/templates/perfil/atualizar.html
{% extends 'perfil/criar.html' %}

{% block titulo %}Atualizar perfil de {{ user }} | {% endblock %}

{% block titulocadastro %}
<h4>Atualizar cadastro</h4>
<p>
    Utilize o formulário a seguir para atualizar seus dados.
</p>
{% endblock %}

perfil/templates/perfil/cart.html
<!doctype html>
<html lang="pt-BR">

    <head>
        <meta charset="utf-8">
        <meta name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.css">
        <link rel="stylesheet" href="assets/custom/css/style.css">

        <title>Hello, world!</title>
    </head>

    <body>
        <nav class="navbar navbar-dark bg-primary navbar-expand-lg">
            <a class="navbar-brand" href="index.html">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home <span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#"
                            id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false">
                            Dropdown
                        </a>
                        <div class="dropdown-menu"
                            aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else
                                here</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#">Disabled</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-cart-link active" href="#">
                            <span class="nav-cart-text mr-1">
                                Carrinho
                            </span>
                            <span class="nav-cart-count mr-1">
                                <strong>109x</strong>
                            </span>
                            <span class="nav-cart-icon mr-2">
                                <i class="fas fa-shopping-cart"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search"
                        placeholder="Search" aria-label="Search">
                    <button class="btn btn-secondary my-2 my-sm-0"
                        type="submit">Search</button>
                </form>
            </div>
        </nav>

        <main class="container mt-4 mb-4">
            <div class="row mt-3">
                <div class="col">
                    <h3>Carrinho de compras</h3>
                    <p class="lead">Os produtos, quantidades e preços que você
                        escolheu.</p>

                    <div class="table-responsive">
                        <table class="table">
                            <tr>
                                <th class="d-none d-lg-block">Imagem</th>
                                <th>Produto</th>
                                <th>V.</th>
                                <th>QTD.</th>
                                <th>Total</th>
                            </tr>

                            <tr>
                                <td class="d-none d-lg-block">
                                    <img class="cart-img"
                                        src="imgs/7eb9d706-b8e3-48d0-957e-25f4a722f944.jpg">
                                </td>
                                <td>
                                    Nome do produto que o cliente está comprando
                                    <a class="ml-3" href="#">
                                        <i
                                            class="fas fa-times-circle text-danger"
                                            aria-hidden="true"></i>
                                    </a>
                                </td>
                                <td>Variação</td>
                                <td>2x</td>
                                <td>R$ 10500,59</td>
                            </tr>

                        </table>
                    </div>
                </div>
            </div>

            <div class="row mt-3">
                <div class="col-lg">
                    <p class='lead'>Total no carrinho</p>

                    <div class='table-responsive'>
                        <table class="table">
                            <tr>
                                <td class="font-weight-bold">Total</td>
                                <td>R$100000</td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="col-lg mt-auto">
                    <a class="btn btn-lg btn-block btn-primary" href="#">
                        Finalizar a compra
                    </a>
                </div>
            </div>

        </main>

        <footer class="container-fluid bg-primary">
            <div class="container text-light">
                <div class="row">
                    <div class="col">
                        <div class="p-1">
                            <span class="align-middle p-1">Feito com
                                Django</span>
                        </div>
                    </div>
                    <div class="col">
                        <div class="p-1 text-right">
                            <span class="align-middle p-1">Por Luiz
                                Otávio</span>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

        <script src="assets/bootstrap/js/jquery-3.2.1.slim.min.js"></script>
        <script src="assets/bootstrap/js/popper.min.js"></script>
        <script src="assets/bootstrap/js/bootstrap.min.js"></script>
        <script defer src="assets/font-awesome/js/all.js"></script>
        <script src="assets/custom/js/scripts.js"></script>
    </body>

</html>

perfil/templates/perfil/criar.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block titulo %}Criar perfil | {% endblock %}

{% block conteudo %}

<div class="row">

    {% if not request.user.is_authenticated %}
    <div class="col-lg mt-3">
        <h4>Login</h4>
        <p>Se você já fez cadastro, basta entrar com seu usuário e senha abaixo:</p>

        <form method="POST" action="{% url 'perfil:login' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="InputUsuario1">Usuário</label>
                <input type="text" name='username' class="form-control" id="InputUsuario1"
                    aria-describedby="usuarioHelp" placeholder="Digite seu usuário">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Senha:</label>
                <input name='password' type="password" class="form-control" id="exampleInputPassword1"
                    placeholder="Digite sua senha">
            </div>
            <button type="submit" class="btn btn-primary btn-block btn-lg">Entrar</button>
        </form>


    </div>
    {% endif %}

    <div class="col-lg mt-3">

        {% block titulocadastro %}
        <h4>Cadastro</h4>
        <p>
            Caso ainda não tenha cadastro, utilize o formulário a seguir para se
            cadastrar
        </p>
        {% endblock %}

        <form method="POST" action="">
            {% csrf_token %}
            {{ userform|crispy }}
            {{ perfilform|crispy }}

            <div class="row">
                <div class="col">
                    <button type="submit" class='btn btn-primary btn-block btn-lg'>
                        Enviar
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

perfil/templates/perfil/index.html
<!doctype html>
<html lang="pt-BR">

    <head>
        <meta charset="utf-8">
        <meta name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.css">
        <link rel="stylesheet" href="assets/custom/css/style.css">

        <title>Hello, world!</title>
    </head>

    <body>
        <nav class="navbar navbar-dark bg-primary navbar-expand-lg">
            <a class="navbar-brand" href="index.html">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home <span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#"
                            id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false">
                            Dropdown
                        </a>
                        <div class="dropdown-menu"
                            aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else
                                here</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#">Disabled</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-cart-link active" href="#">
                            <span class="nav-cart-text mr-1">
                                Carrinho
                            </span>
                            <span class="nav-cart-count mr-1">
                                <strong>109x</strong>
                            </span>
                            <span class="nav-cart-icon mr-2">
                                <i class="fas fa-shopping-cart"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search"
                        placeholder="Search" aria-label="Search">
                    <button class="btn btn-secondary my-2 my-sm-0"
                        type="submit">Search</button>
                </form>
            </div>
        </nav>

        <main class="container mt-4 mb-4">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card-columns">

                        <div class="card">
                            <img class="card-img-top" src="imgs/squared.jpg"
                                alt="Card image cap">
                            <div class="card-body">
                                <h5 class="card-title">Card title that wraps to
                                    a new line</h5>
                                <p class="card-text">This is a longer card with
                                    supporting text below as a natural lead-in
                                    to additional content. This content is a
                                    little bit longer.</p>
                                <div
                                    class="container product-price-block text-center">
                                    <span class="product-price">
                                        R$ 54,90
                                    </span>
                                    <span class="product-old-price text-muted">
                                        R$ 99,90
                                    </span>
                                </div>
                            </div>
                            <div
                                class="card-footer bg-transparent border-top-light-custom text-center">
                                <a href="post.html"
                                    class="btn btn-primary btn-sm m-1 btn-block">
                                    <i class="fa fa-shopping-cart"
                                        aria-hidden="true"></i>
                                    Comprar
                                </a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </main>

        <footer class="container-fluid bg-primary">
            <div class="container text-light">
                <div class="row">
                    <div class="col">
                        <div class="p-1">
                            <span class="align-middle p-1">Feito com
                                Django</span>
                        </div>
                    </div>
                    <div class="col">
                        <div class="p-1 text-right">
                            <span class="align-middle p-1">Por Luiz
                                Otávio</span>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

        <script src="assets/bootstrap/js/jquery-3.2.1.slim.min.js"></script>
        <script src="assets/bootstrap/js/popper.min.js"></script>
        <script src="assets/bootstrap/js/bootstrap.min.js"></script>
        <script defer src="assets/font-awesome/js/all.js"></script>
        <script src="assets/custom/js/scripts.js"></script>
    </body>

</html>